# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FireBaseDemo7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBaseDemo7
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

end
